import React from "react";
import Link from "next/link";
import logo from "../../public/main_logo.png";
import Image from "next/image";
import styles from "./signin.module.css";

const Signin = () => {
  return (
    <>
      <head>
        <title>Jobly - find your dream job </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <div className={styles.logo_wrapper}>
        <Link href="/" passHref>
          <Image src={logo} alt="jobly logo" />
        </Link>
      </div>
      <div className={styles.form_wrapper}>
        <div className={styles.wrapper}>
          <div className={styles.form_label}>
            <h1>Sign In</h1>
          </div>
          <form action="">
            <input type="email" placeholder="Email" />
            <input type="password" placeholder="Password" />
            <button type="submit">Sign In</button>
            <div className={styles.terms}>
              <input type="checkbox" />
              <p>Kep me signed in.</p>
            </div>
            <div className={styles.flex}>
              <div className={styles.line}></div>
              <div>or</div>
              <div className={styles.line}></div>
            </div>
            <div className={styles.googlebtn}>
              <Link href="https://www.google.com/" passHref>
                <button>Sign Up With Google</button>
              </Link>
              <p>
                Don't have an account yet?
                <Link href="../sign-up/sign-up" passHref>
                  <span>Sign Up</span>
                </Link>
              </p>
            </div>
          </form>
        </div>
      </div>
    </>
  );
};

export default Signin;
